/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _diplomski_H_
#define _diplomski_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/splitLink.h>
#include <include/link_api/selectLink.h>
#include <include/link_api/nullLink.h>
#include <include/link_api/vpeLink.h>
#include <include/link_api/algorithmLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

#include <include/link_api/algorithmLink_warpImg.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    SplitLinkID;
       UInt32    SelectLinkID;
       UInt32    VPE_2LinkID;
       UInt32    IPCOut_IPU1_0_A15_0_1LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    NullLinkID;
       UInt32    VPE_1LinkID;
       UInt32    IPCOut_IPU1_0_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Alg_WarpImgLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_0LinkID;
       UInt32    Display_CFLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       SplitLink_CreateParams                  SplitPrm;
       SelectLink_CreateParams                 SelectPrm;
       VpeLink_CreateParams                    VPE_2Prm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_1Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       NullLink_CreateParams                   NullPrm;
       VpeLink_CreateParams                    VPE_1Prm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       AlgorithmLink_WarpImgCreateParams       Alg_WarpImgPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_0Prm;
       DisplayLink_CreateParams                Display_CFPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} diplomskiObj;

Void diplomski_SetLinkId(diplomskiObj *pObj);

Void diplomski_ResetLinkPrms(diplomskiObj *pObj);

Void diplomski_SetPrms(diplomskiObj *pObj);

Void diplomski_ConnectLinks(diplomskiObj *pObj);

Int32 diplomski_Create(diplomskiObj *pObj, Void *appObj);

Int32 diplomski_Start(diplomskiObj *pObj);

Int32 diplomski_Stop(diplomskiObj *pObj);

Int32 diplomski_Delete(diplomskiObj *pObj);

Void diplomski_printBufferStatistics(diplomskiObj *pObj);

Void diplomski_printStatistics(diplomskiObj *pObj);

Void diplomski_SetAppPrms(diplomskiObj *pObj, Void *appObj);

#endif /* _diplomski_H_ */
